worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 100M;

    server {
        listen       80;
        server_name  api.abfun.me;

        # ACME Challenge for Certbot
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redirect all other traffic to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen       443 ssl;
        server_name  api.abfun.me;

        ssl_certificate /etc/letsencrypt/live/api.abfun.me/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.abfun.me/privkey.pem;

        # 用户服务
        location /api/v1/user/ {
            proxy_pass http://user-service:8081/api/v1/user/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 视频服务
        location /api/v1/videos {
            proxy_pass http://video-service:8082/api/v1/videos;
            proxy_set_header Host $host;
        }
        location /api/v1/tags {
            proxy_pass http://video-service:8082/api/v1/tags;
        }

        # 弹幕服务 (WebSocket)
        location /api/v1/danmaku/ {
            proxy_pass http://danmaku-service:8083/api/v1/danmaku/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # 互动服务
        location /api/v1/interaction/ {
            proxy_pass http://interaction-service:8084/api/v1/interaction/;
        }
        
        # 本地文件存储映射
        location /uploads/ {
             alias /data/uploads/;
             autoindex off;
             expires 30d;
             add_header Cache-Control "public";
        }
    }
}
