version = 5.1.0
archive_dir = /etc/letsencrypt/archive/api.abfun.me
cert = /etc/letsencrypt/live/api.abfun.me/cert.pem
privkey = /etc/letsencrypt/live/api.abfun.me/privkey.pem
chain = /etc/letsencrypt/live/api.abfun.me/chain.pem
fullchain = /etc/letsencrypt/live/api.abfun.me/fullchain.pem
[renewalparams]
account = 1d2cb87ba934691c7b05dbdd77ca3baf
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
api.abfun.me = /var/www/certbot
